### ISSUE TITLE
listings.json

### ISSUE THREAD

**Issue by larsdpeder** [simonpacis/DBA-Reposter#1]
----error on win10---- 

File "C:\Users\Workstation\Downloads\DBA-Reposter-master\DBA-Reposter-master\dbareposter.py", line 161, in <module>
    if(os.stat("listings.json").st_size == 0):
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'listings.json'

-----------------

listings.json is created manually in the same folder but i get same error message

**Comment by simonpacis** [comment]
Issue fixed.
