### ISSUE TITLE
Fejl og forslag

### ISSUE THREAD

**Issue by fsjuhl** [simonpacis/DBA-Reposter#3]
Fedt at du stadig opdatere scriptet :)

En fejl jeg har opdaget er, at billederne ikke passer med opsalgne.. Der er f.eks. et opslag med billeder fra 3 andre opslag.

Et forslag:
Automatisk sæt opslags pakken til 2 (premium) hvis brugeren har dba+, som kan udfanges https://api.dba.dk/api/v2/user/profile, som du allerede requester, under summary > attributes > is-dba-plus som så er true eller false.

Andet forslag:
Mulighed for at reposte opslag med kommentare.

**Comment by fsjuhl** [comment]
Huskede lige forkert. Det er pakken nummer 3

**Comment by simonpacis** [comment]
Tak for forslagene. Altså, som i at den uploader forkerte billeder til et opslag, er det sådan du mener?

I forhold til dine forslag lyder det som en god idé at kunne sætte pakker for opslag. Du er velkommen til at se om du kan finde lidt rundt i koden og tilføje det. Evt. med et ekstra argument (de håndteres meget simpelt på linje 156-169), som kan sætte standard pakken for repost af opslag.

Scriptet er lidt af et hackscript, som blev smækket sammen på en eftermiddag, så overordnet set kunne det godt trænge en optimering, men jeg er desværre ret tidspresset, så har kun mulighed for små justeringer hist og her. Tak for forslaget; hvis tid åbner sig op skal jeg nok se om jeg kan implementere det, ellers er du velkommen til at give det et forsøg.

**Comment by fsjuhl** [comment]
Første opslag virker, men derefter uploader den ikke billederne. Den henter dem dog.
Skal prøve :)

**Comment by simonpacis** [comment]
Aha, jeg tror at jeg har en anelse om hvad der forårsager den bug. Jeg får kigget på at fikse den i morgen formiddag. :-)

**Comment by fsjuhl** [comment]
Super fedt!

**Comment by fsjuhl** [comment]
Ved ikke helt hvordan man bruger GIT, men dette burde gøre det :)

På linje 134:
`"bundleTypeId": package`

På linje 154:
       ` package = 4`

På linje 173:

        elif argu == "--premium":
            if(val.lower() == "true"):
                package = 3
                print("Package tier set to premium")
            else:
                package = 4
                print("Package tier set to free")

**Comment by simonpacis** [comment]
Tak for koden, den er hermed implementeret. Har ikke selv DBA+, så håber at det fungerer.

Jeg kigger på billedebug i morgen.

**Comment by simonpacis** [comment]
Alle foreslag tilføjet, og bug fixed.
