### ISSUE TITLE
Reposter ikke nogle opslag

### ISSUE THREAD

**Issue by fsjuhl** [simonpacis/DBA-Reposter#5]
Jeg har lige kørt den på alle mine opslag med --keep=0 og jeg startede med at have 33 opslag, men nu har jeg kun 24 :/ Der var ikke noget mystisk i konsolen eller noget

**Comment by simonpacis** [comment]
Hvis nogle af de listings var blevet kørt før, og derfor havde deres id gemt i listings.json, kan det sagtens tænkes at det har gjort at nogle af dine opslag ikke blev repostet, fordi scriptet troede at de allerede var blevet repostet. Har du nogen ide om indholdet af din listings.json før du kørte scriptet?

**Comment by fsjuhl** [comment]
Ja, det kan nok godt passe. Jeg kørte den nemlig først, hvor den ikke postede som premium, så stoppede jeg den og slettede billederne, og der havde jeg ikke skrevet noget --keep argument. Så må jeg bare slå dem op igen :)

**Comment by simonpacis** [comment]
Ellers er en god idé at deaktivere opslag, så du kun har et par stykker aktive du kører test på, så du er sikker på at det er bugfree, inden du kører på alle dine opslag. Eller opret en anden account, som en test account.

Held og lykke med det. Skriv endelig hvis du finder flere bugs :)
