### ISSUE TITLE
Got old version error from api.dba.dk - Updated dbaapikey and user-agent

### ISSUE THREAD

**Issue by mcj116** [simonpacis/DBA-Reposter#6]
With current version, I got old version error response from api.dba.dk, updated dbaapikey and user-agent. And the nice script runs agian.
New header values used:
dbaapikey: 93d8cbae-ae89-47bb-a423-08d646555519
User-Agent: dba/5.9 iPhone 12.1 (iPhone10,6)

**Comment by simonpacis** [comment]
Thank you. Fixed. :-)
