### ISSUE TITLE
New dbaapikey

### ISSUE THREAD

**Issue by Naja415** [simonpacis/DBA-Reposter#7]
Hi! I get 403 response on the key you listed here. Do you know where to get the newest apikey? BR

**Comment by Naja415** [comment]
I update the get request with useragent and then it worked.

**Comment by simonpacis** [comment]
Great to hear! Let me know which useragent you used, so I can update this projcet.

Regards,
Simon

**Comment by alundkvist** [comment]
Any way to get updated dbaapikey and useragent?

**Comment by simonpacis** [comment]
Hello alundkvist,

Download [https://www.charlesproxy.com](https://www.charlesproxy.com), and follow [https://www.charlesproxy.com/documentation/ios/](https://www.charlesproxy.com/documentation/ios/) to listen in on the requests the DBA app sends to the server.

Within these requests you can find the dbaapikey and useragent.

I might do it sometime, but am too busy to do it atm.

Thank you,
Simon

**Comment by DinRigtigeFar** [comment]
Hi Simon
Did you find time to get the new key and useragent?

**Comment by simonpacis** [comment]
Hi,

Unfortunately not, but if you install Charles, please feel free to get the new key and useragent, and upload it here.

Thank you,
Simon
