### ISSUE TITLE
Oprettelse af DBA scrapper

### ISSUE THREAD

**Issue by EMCK3N** [simonpacis/DBA-Reposter#8]
Hej Simon, 

Jeg er i gang med at lave en scrapper til DBA, som skal samle annonce data til et projekt.
Jeg ville høre hvordan du fandt DBA api nøglen, og om du ved om man kan få adgang til de data via APIen.

**Comment by simonpacis** [comment]
Hej EMCK3N

Jeg huggede DBA api nøglen fra DBA appen på min telefon. Du kan bruge sådan noget som [WireShark](https://www.wireshark.org/) eller [Charles](https://www.charlesproxy.com/) til at aflure de requests som appen laver til serveren. Der kan du finde API nøglen og andet info.

Jeg ved ikke om du kan finde annonce data, det har jeg ikke undersøgt. Men du kan sagtens tilgå APIen med den data du får fat i fra WireShark/Charles.

Der er mange gode tutorials på internettet. Det er slet ikke så svært som det ser ud!

Held og lykke.

Mvh.
Simon Pacis
